/**
 * ListenerToken - A wrapper around a UUID token string that provides
 * a convenient remove() method.
 *
 * This class represents a listener token returned when adding a change listener.
 * It matches the native iOS and Android ListenerToken APIs.
 *
 * IMPORTANT: The remove() method calls the generic listenerToken_Remove bridge
 * method, making it independent of specific remove methods (collection_RemoveChangeListener,
 * query_RemoveChangeListener, etc.) which may be deprecated in the future.
 *
 * Naming Convention:
 * - uuidToken: The UUID string identifier (e.g., "listener-abc-123")
 * - cblListenerToken: An instance of this ListenerToken class
 * - nativeToken: The native iOS/Android ListenerToken object
 *
 * @example
 * ```typescript
 * // Add a listener - get a CBL ListenerToken object
 * const cblListenerToken = await collection.addChangeListener((change) => {
 *   console.log('Changed!', change.documentIDs);
 * });
 *
 * // Remove the listener
 * await cblListenerToken.remove();
 * ```
 */
export declare class ListenerToken {
    /**
     * The UUID string that identifies this listener in the bridge.
     * Generated by React Native (TypeScript side).
     * Example: "listener-abc-123-def-456"
     */
    private readonly _uuidToken;
    /**
     * Callback function that removes the listener.
     * This function calls the GENERIC listenerToken_Remove bridge method.
     */
    private readonly _removeCallbackFunction;
    /**
     * Flag indicating whether remove() has been called.
     * Prevents double-removal.
     */
    private _isRemovedFlag;
    /**
     * Creates a new ListenerToken.
     *
     * @param uuidToken - The UUID string identifier (e.g., "listener-abc-123")
     * @param removeCallbackFunction - Function to call when remove() is invoked
     *
     * @internal - Users should not call this directly. It's called by
     *             Collection, Query, and Replicator classes.
     */
    constructor(uuidToken: string, removeCallbackFunction: () => Promise<void>);
    /**
     * Removes the listener associated with this token.
     *
     * This is the primary method for removing listeners. It:
     * 1. Checks if already removed (no-op if true)
     * 2. Calls the remove callback function
     * 3. The callback calls the GENERIC listenerToken_Remove bridge method
     * 4. The bridge looks up the listener by UUID in unified storage
     * 5. The bridge retrieves the native token and its type from metadata
     * 6. The bridge calls nativeToken.remove()
     * 7. Marks this token as removed
     *
     * Safe to call multiple times - subsequent calls after the first are no-ops.
     *
     * @returns Promise that resolves when the listener is removed
     *
     * @example
     * ```typescript
     * const cblListenerToken = await collection.addChangeListener(...);
     *
     * // Later, remove the listener
     * await cblListenerToken.remove();
     *
     * // Calling again is safe (does nothing)
     * await cblListenerToken.remove(); // No error, just returns immediately
     * ```
     */
    remove(): Promise<void>;
    /**
     * Gets the underlying UUID token string.
     *
     * This is provided for:
     * - Internal use by Collection/Query/Replicator classes
     * - Backward compatibility
     * - Debugging (to see what the UUID is)
     *
     * Most users won't need this - just call remove() instead!
     *
     * @returns The UUID token string (e.g., "listener-abc-123")
     *
     * @example
     * ```typescript
     * const cblListenerToken = await collection.addChangeListener(...);
     * console.log('UUID:', cblListenerToken.getUuidToken()); // "listener-abc-123"
     * ```
     */
    getUuidToken(): string;
    /**
     * Checks if this listener has been removed.
     *
     * @returns true if remove() has been called, false otherwise
     *
     * @example
     * ```typescript
     * const cblListenerToken = await collection.addChangeListener(...);
     * console.log(cblListenerToken.isRemoved()); // false
     *
     * await cblListenerToken.remove();
     * console.log(cblListenerToken.isRemoved()); // true
     * ```
     */
    isRemoved(): boolean;
}
//# sourceMappingURL=listener-token.d.ts.map